<a href="https://colab.research.google.com/github/bxbee/MACHINE_LEARNING/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([2,3,7])
print(A)
print(B)


[1 2 3]
[2 3 7]


In [2]:
A= np.arange(2,20,2)
print(A)

[ 2  4  6  8 10 12 14 16 18]


In [5]:
a = [12,2,22,12]
print(a)

{2, 12, 22}


In [8]:
b=np.array(a)
print(b)

{2, 12, 22}


In [10]:
t=(12,2,21,43)
c=np.array(t)
print(c)

[12  2 21 43]


In [14]:
## Create a Matrix of specified Data type and shape (or Size ) filled With ones
A=np.ones((4,5),dtype=np.int16 )
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
rand = np.random.randint(0,5,(10,2))
print(rand)

[[3 1]
 [0 2]
 [4 2]
 [0 4]
 [1 2]
 [4 3]
 [4 2]
 [2 4]
 [2 2]
 [2 4]]


In [26]:
Rand1= np.random.rand(10,2)
print(Rand1)

[[0.299667   0.78080058]
 [0.97842291 0.7645113 ]
 [0.89778464 0.12551194]
 [0.59246485 0.11691828]
 [0.95270106 0.82913276]
 [0.82699929 0.91966286]
 [0.0307009  0.32847979]
 [0.7352638  0.35513965]
 [0.53184679 0.18805734]
 [0.43516359 0.11833815]]


In [32]:
arr = np.array([10, 2, 4, 1])
arr2 = np.array([13, 2, 3, 1])

print(arr)
print(arr2)


[10  2  4  1]
[13  2  3  1]


In [39]:
##Convert into  1 Dimensional Array
arr3 = np.array([[2,4,1],[7,5,9]])
arr4=arr3.flatten()
print(arr4)

[2 4 1 7 5 9]


In [43]:
##Convert into  1 Dimensional Array using Reshape
arr6 = np.array([[9,2,1],[6,45,9]])
arr5=arr6.reshape(-1)
print(arr5)

[ 9  2  1  6 45  9]


In [44]:
##Convert into 1 dimensional Array using ravel()
arr7 = np.array([[1, 2], [3, 4]])
arr1d = arr7.ravel()
print(arr1d)   # [1 2 3 4]

[1 2 3 4]


In [54]:
## Array Slicing
Arrr=np.array([0,1,2,3,4,5,6,7,8,9])
print("Art[3:6]=",Arrr[3:6])
print(["Art[1::2]=",Arrr[1::2]])

Art[3:6]= [3 4 5]
['Art[1::2]=', array([1, 3, 5, 7, 9])]


In [55]:
##Array Appending (use append)
Arr1=np.array([12,2,23,45,89])
Arr2=np.array([1,2,3,4,5])
print("Appended Array is : \n")
Arrr3=np.append(Arr1,Arr2)
print(Arrr3)

Appended Array is : 

[12  2 23 45 89  1  2  3  4  5]


In [60]:
##using axis append array
Arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr4=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Appended Array using Axis \n")
Arrr4=np.append(Arr3,Arr4,axis=1)
print(Arrr4)

Appended Array using Axis 

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [68]:
##Array split using operator


arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
parts = np.split(arr, 3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [74]:
arr = np.arange(16).reshape((4,4))

left,right = np.hsplit(arr,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
