<a href="https://colab.research.google.com/github/bxbee/MACHINE_LEARNING/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([2,3,7])
print(A)
print(B)


[1 2 3]
[2 3 7]


In [2]:
A= np.arange(2,20,2)
print(A)

[ 2  4  6  8 10 12 14 16 18]


In [5]:
a = [12,2,22,12]
print(a)

{2, 12, 22}


In [8]:
b=np.array(a)
print(b)

{2, 12, 22}


In [10]:
t=(12,2,21,43)
c=np.array(t)
print(c)

[12  2 21 43]


In [14]:
## Create a Matrix of specified Data type and shape (or Size ) filled With ones
A=np.ones((4,5),dtype=np.int16 )
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
