<a href="https://colab.research.google.com/github/bxbee/MACHINE_LEARNING/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([2,3,7])
print(A)
print(B)


[1 2 3]
[2 3 7]


In [ ]:
A= np.arange(2,20,2)
print(A)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
a = [12,2,22,12]
print(a)

{2, 12, 22}


In [ ]:
b=np.array(a)
print(b)

{2, 12, 22}


In [ ]:
t=(12,2,21,43)
c=np.array(t)
print(c)

[12  2 21 43]


In [ ]:
## Create a Matrix of specified Data type and shape (or Size ) filled With ones
A=np.ones((4,5),dtype=np.int16 )
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
rand = np.random.randint(0,5,(10,2))
print(rand)

[[3 1]
 [0 2]
 [4 2]
 [0 4]
 [1 2]
 [4 3]
 [4 2]
 [2 4]
 [2 2]
 [2 4]]


In [ ]:
Rand1= np.random.rand(10,2)
print(Rand1)

[[0.299667   0.78080058]
 [0.97842291 0.7645113 ]
 [0.89778464 0.12551194]
 [0.59246485 0.11691828]
 [0.95270106 0.82913276]
 [0.82699929 0.91966286]
 [0.0307009  0.32847979]
 [0.7352638  0.35513965]
 [0.53184679 0.18805734]
 [0.43516359 0.11833815]]


In [ ]:
arr = np.array([10, 2, 4, 1])
arr2 = np.array([13, 2, 3, 1])

print(arr)
print(arr2)


[10  2  4  1]
[13  2  3  1]


In [ ]:
##Convert into  1 Dimensional Array
arr3 = np.array([[2,4,1],[7,5,9]])
arr4=arr3.flatten()
print(arr4)

[2 4 1 7 5 9]


In [ ]:
##Convert into  1 Dimensional Array using Reshape
arr6 = np.array([[9,2,1],[6,45,9]])
arr5=arr6.reshape(-1)
print(arr5)

[ 9  2  1  6 45  9]


In [ ]:
##Convert into 1 dimensional Array using ravel()
arr7 = np.array([[1, 2], [3, 4]])
arr1d = arr7.ravel()
print(arr1d)   # [1 2 3 4]

[1 2 3 4]


In [ ]:
## Array Slicing
Arrr=np.array([0,1,2,3,4,5,6,7,8,9])
print("Art[3:6]=",Arrr[3:6])
print(["Art[1::2]=",Arrr[1::2]])

Art[3:6]= [3 4 5]
['Art[1::2]=', array([1, 3, 5, 7, 9])]


In [ ]:
##Array Appending (use append)
Arr1=np.array([12,2,23,45,89])
Arr2=np.array([1,2,3,4,5])
print("Appended Array is : \n")
Arrr3=np.append(Arr1,Arr2)
print(Arrr3)

Appended Array is : 

[12  2 23 45 89  1  2  3  4  5]


In [ ]:
##using axis append array
Arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr4=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Appended Array using Axis \n")
Arrr4=np.append(Arr3,Arr4,axis=1)
print(Arrr4)

Appended Array using Axis 

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [9]:
import numpy as np

Arr5 = np.array([1, 2, 3, 4, 5])
print("Original Data \n")
print(Arr5)

# Insert value 99 at index 2
AA = np.insert(Arr5, 2, 100)
print("Modified Data \n")
print(AA)

Original Data 

[1 2 3 4 5]
Modified Data 

[  1   2 100   3   4   5]


In [11]:
AA1 = np.delete(Arr5, 3)
print("Modified Data \n")
print(AA1)

Modified Data 

[1 2 3 5]


In [13]:
AA2 = np.arange(9)
print("Original Array",AA2)
print("Shape",AA2.shape)
print("Dimension",AA2)

Original Array [0 1 2 3 4 5 6 7 8]
Shape (9,)
Dimension [0 1 2 3 4 5 6 7 8]


In [20]:
arr = np.array([[1,2,3,4],[4,5,6,7]])

print("After original Array",arr)
Arr7=np.delete(arr,0,axis = 1)
print("After Modified Array",Arr7)
print(arr.shape)

After original Array [[1 2 3 4]
 [4 5 6 7]]
After Modified Array [[2 3 4]
 [5 6 7]]
(2, 4)


In [21]:
Arr = np.ones(10)
if (arr.size == 0):
    print("Array is empty")
else:
    print("Array is not empty")


Array is not empty


In [23]:
arr = np.array([[1,2,3,4,12,24,16,45,3,2],[4,5,6,7,12,45,2,34,23,34]])

In [25]:
Arr =  np.arange(12).reshape(3,4)
print("the array is :")
print(Arr)
print("Length of the array is : ",Arr.size)

the array is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Length of the array is :  12


In [30]:
A = np.arange(10)
print("The array is",A)
index = np.where(A==8)
print("The index of the value is :",index[0])


The array is [0 1 2 3 4 5 6 7 8 9]
The index of the value is : [8]


In [35]:
Arr9= np.array([4,2,5,2,1,6])
print("The array is",Arr9)
asc=np.sort(Arr9)
print("Ascending Order", asc)
desc=np.sort(Arr9) [::-1]
print("Sorted Array",desc)

The array is [4 2 5 2 1 6]
Ascending Order [1 2 2 4 5 6]
Sorted Array [6 5 4 2 2 1]


In [40]:
import numpy
Arr12 = numpy.array([450,432,654,234,232,674,1023,236,765])
Arr_max=Arr12.max()
Arr_min=Arr12.min()
Arr_nor=(Arr12-Arr_min)/(Arr_max-Arr_min)
print("The original array is",Arr12)
print(Arr_max)
print(Arr_min)
print("The normalized array is",Arr_nor)

The original array is [ 450  432  654  234  232  674 1023  236  765]
1023
232
The normalized array is [0.27560051 0.2528445  0.5335019  0.00252845 0.         0.55878635
 1.         0.00505689 0.67383059]


In [42]:
Arr13 = np.array([1, 2, 3, 4, 5])
print("Original Array :")
print(Arr13)
print("Transposed Array",Arr13.T)

Original Array :
[1 2 3 4 5]
Transposed Array [1 2 3 4 5]


In [48]:
Arr14 = np.array([[1, 2, 3, 4, 5],
 [6,5,3,2,1],
  [6,5,4,3,3]])
print("Original Array :")
print(Arr14)
print("Transposed Array",np.transpose(Arr14))


Original Array :
[[1 2 3 4 5]
 [6 5 3 2 1]
 [6 5 4 3 3]]
Transposed Array [[1 6 6]
 [2 5 5]
 [3 3 4]
 [4 2 3]
 [5 1 3]]


In [52]:
arr14 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [11,22,33,44]])
print("Original Array :")
print(arr14)
print("Transposed Array",arr14.T)
print(Arr14.shape)


Original Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]
Transposed Array [[ 1  5 11]
 [ 2  6 22]
 [ 3  7 33]
 [ 4  8 44]]
(3, 5)


In [54]:
print(arr14.T.shape)

(4, 3)


In [67]:
import numpy as np


arr14 = np.arange(27).reshape(3,3,3)

print("3D Array is:\n", arr14)
print("\nShape of the array:", arr14.shape)

print("\nDiagonal elements for axis1=1 and axis2=2:")
print(arr14.diagonal(axis1=1, axis2=2))

3D Array is:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Shape of the array: (3, 3, 3)

Diagonal elements for axis1=1 and axis2=2:
[[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]
